CREATE DATABASE BLOG;
CREATE TABLE AIR_QUALITY(
	AIR_QUALITY_ID INT(11) NOT NULL AUTO_INCREMENT,	-- ID
	CITY_NAME VARCHAR(20) NOT NULL DEFAULT '',	-- 城市	
	PROVINCE_NAME VARCHAR(20) NOT NULL DEFAULT '',	-- 省份
	DEPOT_NAME VARCHAR(20) NOT NULL DEFAULT '',	-- 区域
	POLLUTION_TYPE VARCHAR(20) NOT NULL DEFAULT '',	-- 污染类型
	POLLUTION_LEVEL VARCHAR(10) DEFAULT -1,		-- 污染级别
	POLLUTION_INDEX INT(4) DEFAULT -1,		-- 空气指数
	AIR_QUALITY VARCHAR(255) NOT NULL DEFAULT '',	-- 空气质量
	DATE_TIME VARCHAR(15) NOT NULL DEFAULT '',	-- 发布日期
	PRIMARY KEY(AIR_QUALITY_ID),
	UNIQUE KEY(CITY_NAME,DATE_TIME,POLLUTION_INDEX)	
)ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=4611;

SELECT CITY_NAME,PROVINCE_NAME,DEPOT_NAME,POLLUTION_TYPE,POLLUTION_LEVEL,POLLUTION_INDEX,AIR_QUALITY,DATE_TIME
	FROM AIR_QUALITY;
